### ISSUE TITLE
Better annotation customisation

### ISSUE THREAD

**Issue by maehler** [hydra-genetics/reports#22]
Custom annotations could be a bit more flexible than they currently are. For example, they could have different colours, the addition of a legend, the type of plot to be used for the annotation (e.g. segment, point, bar), and whether or not the annotation should have a text component.

This is something that could be made pretty complex, with a proportional amount of work in order to achieve it. As a starting point, being able to change colours and add a legend would be enough. The [bed file specification actually already contains a colour field](https://en.wikipedia.org/wiki/BED_(file_format)#Description), so that could possibly be used. That would enable different colours within a single file, but that might be too much. A simpler option would be to extend the config to include name, colour, if a legend should be shown, something like this:

```yaml
merge_cnv_json:
  - annotations:
    - name: Gene
      bed: path/to/genes.bed
      colour: forestgreen
      opacity: 0.3
      legend: false
      labels: true
    - name: Centromere
      bed: path/to/centromeres.bed
      colour: gold
      opacity: 0.2
      legend: true
      labels: true
```
